spring:
  datasource:
    url: jdbc:mysql://thefaco-beverage.cry75t3vojiz.ap-northeast-2.rds.amazonaws.com:3306/thefaco-beverage
    username: admin
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace